[[constraint]]
  branch = "master"
  name = "github.com/akaspin/cut"

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/logx"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-systemd"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"
